module.exports = function toReadable (number) {
  const numbers = {
    0: 'zero',
    1: 'one',
    2: 'two',
    3: 'three',
    4: 'four',
    5: 'five',
    6: 'six',
    7: 'seven',
    8: 'eight',
    9: 'nine',
    10: 'ten',
    11: 'eleven',
    12: 'twelve',
    13: 'thirteen',
    14: 'fourteen',
    15: 'fifteen',
    16: 'sixteen',
    17: 'seventeen',
    18: 'eighteen',
    19: 'nineteen',
    20: 'twenty',
    30: 'thirty',
    40: 'forty',
    50: 'fifty',
    60: 'sixty',
    70: 'seventy',
    80: 'eighty',
    90: 'ninety',
  }

  let unit = numbers[number.toString()[2]]
  let dozens = numbers[number.toString()[1]*10]
  let hundreds = numbers[number.toString()[0]] + ' hundred'
  let twoDigitFirst = numbers[number.toString()[0]*10]
  let twoDigitTwo = numbers[number.toString()[1]]

  // Те числа, которые есть в массиве
  if (numbers[number]) {
    return numbers[number]

  // Если число больше или равное 1000
  } else if (number >= 1000){
    return 'Your number is greater than 999'

  // Числа 100, 200, 300 ... 900
  } else if (number % 100 === 0) {
    return hundreds

  // Числа больше 101
  } else if (number / 100 > 1){
    return hundreds + ' ' + (numbers[number % 100] ? numbers[number % 100] : dozens + ' ' + unit)

  // Остальные числа, 21-29, 31-39, ... 91-99
  } else {
    return twoDigitFirst + ' ' + twoDigitTwo
  }
}

// function toReadable (number) {
//   const numbers = {
//     0: 'zero',
//     1: 'one',
//     2: 'two',
//     3: 'three',
//     4: 'four',
//     5: 'five',
//     6: 'six',
//     7: 'seven',
//     8: 'eight',
//     9: 'nine',
//     10: 'ten',
//     11: 'eleven',
//     12: 'twelve',
//     13: 'thirteen',
//     14: 'fourteen',
//     15: 'fifteen',
//     16: 'sixteen',
//     17: 'seventeen',
//     18: 'eighteen',
//     19: 'nineteen',
//     20: 'twenty',
//     30: 'thirty',
//     40: 'forty',
//     50: 'fifty',
//     60: 'sixty',
//     70: 'seventy',
//     80: 'eighty',
//     90: 'ninety',
//   }

//   let unit = numbers[number.toString()[2]]
//   let dozens = numbers[number.toString()[1]*10]
//   let hundreds = numbers[number.toString()[0]] + ' hundred'
//   let twoDigitFirst = numbers[number.toString()[0]*10]
//   let twoDigitTwo = numbers[number.toString()[1]]

//   // Те числа, которые есть в массиве
//   if (numbers[number]) {
//     return numbers[number]

//   // Если число больше или равное 1000
//   } else if (number >= 1000){
//     return 'Your number is greater than 999'

//   // Числа 100, 200, 300 ... 900
//   } else if (number % 100 === 0) {
//     return hundreds

//   // Числа больше 101
//   } else if (number / 100 > 1){
//     return hundreds + ' ' + (numbers[number % 100] ? numbers[number % 100] : dozens + ' ' + unit)

//   // Остальные числа, 21-29, 31-39, ... 91-99
//   } else {
//     return twoDigitFirst + ' ' + twoDigitTwo
//   }
// }

// console.log(toReadable(0)) // 'zero'
// console.log(toReadable(1)) // 'one'
// console.log(toReadable(2)) // 'two'
// console.log(toReadable(3)) // 'three'
// console.log(toReadable(4)) // 'four'
// console.log(toReadable(5)) // 'five'
// console.log(toReadable(6)) // 'six'
// console.log(toReadable(7)) // 'seven'
// console.log(toReadable(8)) // 'eight'
// console.log(toReadable(9)) // 'nine'
// console.log(toReadable(10)) // 'ten'
// console.log(toReadable(11)) // 'eleven'
// console.log(toReadable(12)) // 'twelve'
// console.log(toReadable(13)) // 'thirteen'
// console.log(toReadable(14)) // 'fourteen'
// console.log(toReadable(15)) // 'fifteen'
// console.log(toReadable(16)) // 'sixteen'
// console.log(toReadable(17)) // 'seventeen'
// console.log(toReadable(18)) // 'eighteen'
// console.log(toReadable(19)) // 'nineteen'
// console.log(toReadable(20)) // 'twenty'
// console.log(toReadable(21)) // 'twenty one'
// console.log(toReadable(22)) // 'twenty two'
// console.log(toReadable(23)) // 'twenty three'
// console.log(toReadable(24)) // 'twenty four'
// console.log(toReadable(25)) // 'twenty five'
// console.log(toReadable(26)) // 'twenty six'
// console.log(toReadable(27)) // 'twenty seven'
// console.log(toReadable(28)) // 'twenty eight'
// console.log(toReadable(29)) // 'twenty nine'
// console.log(toReadable(30)) // 'thirty'
// console.log(toReadable(31)) // 'thirty one'
// console.log(toReadable(32)) // 'thirty two'
// console.log(toReadable(33)) // 'thirty three'
// console.log(toReadable(34)) // 'thirty four'
// console.log(toReadable(35)) // 'thirty five'
// console.log(toReadable(36)) // 'thirty six'
// console.log(toReadable(37)) // 'thirty seven'
// console.log(toReadable(38)) // 'thirty eight'
// console.log(toReadable(39)) // 'thirty nine'
// console.log(toReadable(40)) // 'forty'
// console.log(toReadable(41)) // 'forty one'
// console.log(toReadable(42)) // 'forty two'
// console.log(toReadable(43)) // 'forty three'
// console.log(toReadable(44)) // 'forty four'
// console.log(toReadable(45)) // 'forty five'
// console.log(toReadable(46)) // 'forty six'
// console.log(toReadable(47)) // 'forty seven'
// console.log(toReadable(48)) // 'forty eight'
// console.log(toReadable(49)) // 'forty nine'
// console.log(toReadable(50)) // 'fifty'
// console.log(toReadable(51)) // 'fifty one'
// console.log(toReadable(52)) // 'fifty two'
// console.log(toReadable(53)) // 'fifty three'
// console.log(toReadable(54)) // 'fifty four'
// console.log(toReadable(55)) // 'fifty five'
// console.log(toReadable(56)) // 'fifty six'
// console.log(toReadable(57)) // 'fifty seven'
// console.log(toReadable(58)) // 'fifty eight'
// console.log(toReadable(59)) // 'fifty nine'
// console.log(toReadable(60)) // 'sixty'
// console.log(toReadable(61)) // 'sixty one'
// console.log(toReadable(62)) // 'sixty two'
// console.log(toReadable(63)) // 'sixty three'
// console.log(toReadable(64)) // 'sixty four'
// console.log(toReadable(65)) // 'sixty five'
// console.log(toReadable(66)) // 'sixty six'
// console.log(toReadable(67)) // 'sixty seven'
// console.log(toReadable(68)) // 'sixty eight'
// console.log(toReadable(69)) // 'sixty nine'
// console.log(toReadable(70)) // 'seventy'
// console.log(toReadable(71)) // 'seventy one'
// console.log(toReadable(72)) // 'seventy two'
// console.log(toReadable(73)) // 'seventy three'
// console.log(toReadable(74)) // 'seventy four'
// console.log(toReadable(75)) // 'seventy five'
// console.log(toReadable(76)) // 'seventy six'
// console.log(toReadable(77)) // 'seventy seven'
// console.log(toReadable(78)) // 'seventy eight'
// console.log(toReadable(79)) // 'seventy nine'
// console.log(toReadable(80)) // 'eighty'
// console.log(toReadable(81)) // 'eighty one'
// console.log(toReadable(82)) // 'eighty two'
// console.log(toReadable(83)) // 'eighty three'
// console.log(toReadable(84)) // 'eighty four'
// console.log(toReadable(85)) // 'eighty five'
// console.log(toReadable(86)) // 'eighty six'
// console.log(toReadable(87)) // 'eighty seven'
// console.log(toReadable(88)) // 'eighty eight'
// console.log(toReadable(89)) // 'eighty nine'
// console.log(toReadable(90)) // 'ninety'
// console.log(toReadable(91)) // 'ninety one'
// console.log(toReadable(92)) // 'ninety two'
// console.log(toReadable(93)) // 'ninety three'
// console.log(toReadable(94)) // 'ninety four'
// console.log(toReadable(95)) // 'ninety five'
// console.log(toReadable(96)) // 'ninety six'
// console.log(toReadable(97)) // 'ninety seven'
// console.log(toReadable(98)) // 'ninety eight'
// console.log(toReadable(99)) // 'ninety nine'
// console.log(toReadable(100)) // 'one hundred'
// console.log(toReadable(101)) // 'one hundred one'
// console.log(toReadable(102)) // 'one hundred two'
// console.log(toReadable(103)) // 'one hundred three'
// console.log(toReadable(104)) // 'one hundred four'
// console.log(toReadable(105)) // 'one hundred five'
// console.log(toReadable(106)) // 'one hundred six'
// console.log(toReadable(107)) // 'one hundred seven'
// console.log(toReadable(108)) // 'one hundred eight'
// console.log(toReadable(109)) // 'one hundred nine'
// console.log(toReadable(110)) // 'one hundred ten'
// console.log(toReadable(111)) // 'one hundred eleven'
// console.log(toReadable(112)) // 'one hundred twelve'
// console.log(toReadable(113)) // 'one hundred thirteen'
// console.log(toReadable(114)) // 'one hundred fourteen'
// console.log(toReadable(115)) // 'one hundred fifteen'
// console.log(toReadable(116)) // 'one hundred sixteen'
// console.log(toReadable(117)) // 'one hundred seventeen'
// console.log(toReadable(118)) // 'one hundred eighteen'
// console.log(toReadable(119)) // 'one hundred nineteen'
// console.log(toReadable(120)) // 'one hundred twenty'
// console.log(toReadable(121)) // 'one hundred twenty one'
// console.log(toReadable(122)) // 'one hundred twenty two'
// console.log(toReadable(123)) // 'one hundred twenty three'
// console.log(toReadable(124)) // 'one hundred twenty four'
// console.log(toReadable(125)) // 'one hundred twenty five'
// console.log(toReadable(126)) // 'one hundred twenty six'
// console.log(toReadable(127)) // 'one hundred twenty seven'
// console.log(toReadable(128)) // 'one hundred twenty eight'
// console.log(toReadable(129)) // 'one hundred twenty nine'
// console.log(toReadable(130)) // 'one hundred thirty'
// console.log(toReadable(131)) // 'one hundred thirty one'
// console.log(toReadable(132)) // 'one hundred thirty two'
// console.log(toReadable(133)) // 'one hundred thirty three'
// console.log(toReadable(134)) // 'one hundred thirty four'
// console.log(toReadable(135)) // 'one hundred thirty five'
// console.log(toReadable(136)) // 'one hundred thirty six'
// console.log(toReadable(137)) // 'one hundred thirty seven'
// console.log(toReadable(138)) // 'one hundred thirty eight'
// console.log(toReadable(139)) // 'one hundred thirty nine'
// console.log(toReadable(140)) // 'one hundred forty'
// console.log(toReadable(141)) // 'one hundred forty one'
// console.log(toReadable(142)) // 'one hundred forty two'
// console.log(toReadable(143)) // 'one hundred forty three'
// console.log(toReadable(144)) // 'one hundred forty four'
// console.log(toReadable(145)) // 'one hundred forty five'
// console.log(toReadable(146)) // 'one hundred forty six'
// console.log(toReadable(147)) // 'one hundred forty seven'
// console.log(toReadable(148)) // 'one hundred forty eight'
// console.log(toReadable(149)) // 'one hundred forty nine'
// console.log(toReadable(150)) // 'one hundred fifty'
// console.log(toReadable(151)) // 'one hundred fifty one'
// console.log(toReadable(152)) // 'one hundred fifty two'
// console.log(toReadable(153)) // 'one hundred fifty three'
// console.log(toReadable(154)) // 'one hundred fifty four'
// console.log(toReadable(155)) // 'one hundred fifty five'
// console.log(toReadable(156)) // 'one hundred fifty six'
// console.log(toReadable(157)) // 'one hundred fifty seven'
// console.log(toReadable(158)) // 'one hundred fifty eight'
// console.log(toReadable(159)) // 'one hundred fifty nine'
// console.log(toReadable(160)) // 'one hundred sixty'
// console.log(toReadable(161)) // 'one hundred sixty one'
// console.log(toReadable(162)) // 'one hundred sixty two'
// console.log(toReadable(163)) // 'one hundred sixty three'
// console.log(toReadable(164)) // 'one hundred sixty four'
// console.log(toReadable(165)) // 'one hundred sixty five'
// console.log(toReadable(166)) // 'one hundred sixty six'
// console.log(toReadable(167)) // 'one hundred sixty seven'
// console.log(toReadable(168)) // 'one hundred sixty eight'
// console.log(toReadable(169)) // 'one hundred sixty nine'
// console.log(toReadable(170)) // 'one hundred seventy'
// console.log(toReadable(171)) // 'one hundred seventy one'
// console.log(toReadable(172)) // 'one hundred seventy two'
// console.log(toReadable(173)) // 'one hundred seventy three'
// console.log(toReadable(174)) // 'one hundred seventy four'
// console.log(toReadable(175)) // 'one hundred seventy five'
// console.log(toReadable(176)) // 'one hundred seventy six'
// console.log(toReadable(177)) // 'one hundred seventy seven'
// console.log(toReadable(178)) // 'one hundred seventy eight'
// console.log(toReadable(179)) // 'one hundred seventy nine'
// console.log(toReadable(180)) // 'one hundred eighty'
// console.log(toReadable(181)) // 'one hundred eighty one'
// console.log(toReadable(182)) // 'one hundred eighty two'
// console.log(toReadable(183)) // 'one hundred eighty three'
// console.log(toReadable(184)) // 'one hundred eighty four'
// console.log(toReadable(185)) // 'one hundred eighty five'
// console.log(toReadable(186)) // 'one hundred eighty six'
// console.log(toReadable(187)) // 'one hundred eighty seven'
// console.log(toReadable(188)) // 'one hundred eighty eight'
// console.log(toReadable(189)) // 'one hundred eighty nine'
// console.log(toReadable(190)) // 'one hundred ninety'
// console.log(toReadable(191)) // 'one hundred ninety one'
// console.log(toReadable(192)) // 'one hundred ninety two'
// console.log(toReadable(193)) // 'one hundred ninety three'
// console.log(toReadable(194)) // 'one hundred ninety four'
// console.log(toReadable(195)) // 'one hundred ninety five'
// console.log(toReadable(196)) // 'one hundred ninety six'
// console.log(toReadable(197)) // 'one hundred ninety seven'
// console.log(toReadable(198)) // 'one hundred ninety eight'
// console.log(toReadable(199)) // 'one hundred ninety nine'
// console.log(toReadable(200)) // 'two hundred'
// console.log(toReadable(201)) // 'two hundred one'
// console.log(toReadable(202)) // 'two hundred two'
// console.log(toReadable(203)) // 'two hundred three'
// console.log(toReadable(204)) // 'two hundred four'
// console.log(toReadable(205)) // 'two hundred five'
// console.log(toReadable(206)) // 'two hundred six'
// console.log(toReadable(207)) // 'two hundred seven'
// console.log(toReadable(208)) // 'two hundred eight'
// console.log(toReadable(209)) // 'two hundred nine'
// console.log(toReadable(210)) // 'two hundred ten'
// console.log(toReadable(211)) // 'two hundred eleven'
// console.log(toReadable(212)) // 'two hundred twelve'
// console.log(toReadable(213)) // 'two hundred thirteen'
// console.log(toReadable(214)) // 'two hundred fourteen'
// console.log(toReadable(215)) // 'two hundred fifteen'
// console.log(toReadable(216)) // 'two hundred sixteen'
// console.log(toReadable(217)) // 'two hundred seventeen'
// console.log(toReadable(218)) // 'two hundred eighteen'
// console.log(toReadable(219)) // 'two hundred nineteen'
// console.log(toReadable(220)) // 'two hundred twenty'
// console.log(toReadable(221)) // 'two hundred twenty one'
// console.log(toReadable(222)) // 'two hundred twenty two'
// console.log(toReadable(223)) // 'two hundred twenty three'
// console.log(toReadable(224)) // 'two hundred twenty four'
// console.log(toReadable(225)) // 'two hundred twenty five'
// console.log(toReadable(226)) // 'two hundred twenty six'
// console.log(toReadable(227)) // 'two hundred twenty seven'
// console.log(toReadable(228)) // 'two hundred twenty eight'
// console.log(toReadable(229)) // 'two hundred twenty nine'
// console.log(toReadable(230)) // 'two hundred thirty'
// console.log(toReadable(231)) // 'two hundred thirty one'
// console.log(toReadable(232)) // 'two hundred thirty two'
// console.log(toReadable(233)) // 'two hundred thirty three'
// console.log(toReadable(234)) // 'two hundred thirty four'
// console.log(toReadable(235)) // 'two hundred thirty five'
// console.log(toReadable(236)) // 'two hundred thirty six'
// console.log(toReadable(237)) // 'two hundred thirty seven'
// console.log(toReadable(238)) // 'two hundred thirty eight'
// console.log(toReadable(239)) // 'two hundred thirty nine'
// console.log(toReadable(240)) // 'two hundred forty'
// console.log(toReadable(241)) // 'two hundred forty one'
// console.log(toReadable(242)) // 'two hundred forty two'
// console.log(toReadable(243)) // 'two hundred forty three'
// console.log(toReadable(244)) // 'two hundred forty four'
// console.log(toReadable(245)) // 'two hundred forty five'
// console.log(toReadable(246)) // 'two hundred forty six'
// console.log(toReadable(247)) // 'two hundred forty seven'
// console.log(toReadable(248)) // 'two hundred forty eight'
// console.log(toReadable(249)) // 'two hundred forty nine'
// console.log(toReadable(250)) // 'two hundred fifty'
// console.log(toReadable(251)) // 'two hundred fifty one'
// console.log(toReadable(252)) // 'two hundred fifty two'
// console.log(toReadable(253)) // 'two hundred fifty three'
// console.log(toReadable(254)) // 'two hundred fifty four'
// console.log(toReadable(255)) // 'two hundred fifty five'
// console.log(toReadable(256)) // 'two hundred fifty six'
// console.log(toReadable(257)) // 'two hundred fifty seven'
// console.log(toReadable(258)) // 'two hundred fifty eight'
// console.log(toReadable(259)) // 'two hundred fifty nine'
// console.log(toReadable(260)) // 'two hundred sixty'
// console.log(toReadable(261)) // 'two hundred sixty one'
// console.log(toReadable(262)) // 'two hundred sixty two'
// console.log(toReadable(263)) // 'two hundred sixty three'
// console.log(toReadable(264)) // 'two hundred sixty four'
// console.log(toReadable(265)) // 'two hundred sixty five'
// console.log(toReadable(266)) // 'two hundred sixty six'
// console.log(toReadable(267)) // 'two hundred sixty seven'
// console.log(toReadable(268)) // 'two hundred sixty eight'
// console.log(toReadable(269)) // 'two hundred sixty nine'
// console.log(toReadable(270)) // 'two hundred seventy'
// console.log(toReadable(271)) // 'two hundred seventy one'
// console.log(toReadable(272)) // 'two hundred seventy two'
// console.log(toReadable(273)) // 'two hundred seventy three'
// console.log(toReadable(274)) // 'two hundred seventy four'
// console.log(toReadable(275)) // 'two hundred seventy five'
// console.log(toReadable(276)) // 'two hundred seventy six'
// console.log(toReadable(277)) // 'two hundred seventy seven'
// console.log(toReadable(278)) // 'two hundred seventy eight'
// console.log(toReadable(279)) // 'two hundred seventy nine'
// console.log(toReadable(280)) // 'two hundred eighty'
// console.log(toReadable(281)) // 'two hundred eighty one'
// console.log(toReadable(282)) // 'two hundred eighty two'
// console.log(toReadable(283)) // 'two hundred eighty three'
// console.log(toReadable(284)) // 'two hundred eighty four'
// console.log(toReadable(285)) // 'two hundred eighty five'
// console.log(toReadable(286)) // 'two hundred eighty six'
// console.log(toReadable(287)) // 'two hundred eighty seven'
// console.log(toReadable(288)) // 'two hundred eighty eight'
// console.log(toReadable(289)) // 'two hundred eighty nine'
// console.log(toReadable(290)) // 'two hundred ninety'
// console.log(toReadable(291)) // 'two hundred ninety one'
// console.log(toReadable(292)) // 'two hundred ninety two'
// console.log(toReadable(293)) // 'two hundred ninety three'
// console.log(toReadable(294)) // 'two hundred ninety four'
// console.log(toReadable(295)) // 'two hundred ninety five'
// console.log(toReadable(296)) // 'two hundred ninety six'
// console.log(toReadable(297)) // 'two hundred ninety seven'
// console.log(toReadable(298)) // 'two hundred ninety eight'
// console.log(toReadable(299)) // 'two hundred ninety nine'
// console.log(toReadable(300)) // 'three hundred'
// console.log(toReadable(301)) // 'three hundred one'
// console.log(toReadable(302)) // 'three hundred two'
// console.log(toReadable(303)) // 'three hundred three'
// console.log(toReadable(304)) // 'three hundred four'
// console.log(toReadable(305)) // 'three hundred five'
// console.log(toReadable(306)) // 'three hundred six'
// console.log(toReadable(307)) // 'three hundred seven'
// console.log(toReadable(308)) // 'three hundred eight'
// console.log(toReadable(309)) // 'three hundred nine'
// console.log(toReadable(310)) // 'three hundred ten'
// console.log(toReadable(311)) // 'three hundred eleven'
// console.log(toReadable(312)) // 'three hundred twelve'
// console.log(toReadable(313)) // 'three hundred thirteen'
// console.log(toReadable(314)) // 'three hundred fourteen'
// console.log(toReadable(315)) // 'three hundred fifteen'
// console.log(toReadable(316)) // 'three hundred sixteen'
// console.log(toReadable(317)) // 'three hundred seventeen'
// console.log(toReadable(318)) // 'three hundred eighteen'
// console.log(toReadable(319)) // 'three hundred nineteen'
// console.log(toReadable(320)) // 'three hundred twenty'
// console.log(toReadable(321)) // 'three hundred twenty one'
// console.log(toReadable(322)) // 'three hundred twenty two'
// console.log(toReadable(323)) // 'three hundred twenty three'
// console.log(toReadable(324)) // 'three hundred twenty four'
// console.log(toReadable(325)) // 'three hundred twenty five'
// console.log(toReadable(326)) // 'three hundred twenty six'
// console.log(toReadable(327)) // 'three hundred twenty seven'
// console.log(toReadable(328)) // 'three hundred twenty eight'
// console.log(toReadable(329)) // 'three hundred twenty nine'
// console.log(toReadable(330)) // 'three hundred thirty'
// console.log(toReadable(331)) // 'three hundred thirty one'
// console.log(toReadable(332)) // 'three hundred thirty two'
// console.log(toReadable(333)) // 'three hundred thirty three'
// console.log(toReadable(334)) // 'three hundred thirty four'
// console.log(toReadable(335)) // 'three hundred thirty five'
// console.log(toReadable(336)) // 'three hundred thirty six'
// console.log(toReadable(337)) // 'three hundred thirty seven'
// console.log(toReadable(338)) // 'three hundred thirty eight'
// console.log(toReadable(339)) // 'three hundred thirty nine'
// console.log(toReadable(340)) // 'three hundred forty'
// console.log(toReadable(341)) // 'three hundred forty one'
// console.log(toReadable(342)) // 'three hundred forty two'
// console.log(toReadable(343)) // 'three hundred forty three'
// console.log(toReadable(344)) // 'three hundred forty four'
// console.log(toReadable(345)) // 'three hundred forty five'
// console.log(toReadable(346)) // 'three hundred forty six'
// console.log(toReadable(347)) // 'three hundred forty seven'
// console.log(toReadable(348)) // 'three hundred forty eight'
// console.log(toReadable(349)) // 'three hundred forty nine'
// console.log(toReadable(350)) // 'three hundred fifty'
// console.log(toReadable(351)) // 'three hundred fifty one'
// console.log(toReadable(352)) // 'three hundred fifty two'
// console.log(toReadable(353)) // 'three hundred fifty three'
// console.log(toReadable(354)) // 'three hundred fifty four'
// console.log(toReadable(355)) // 'three hundred fifty five'
// console.log(toReadable(356)) // 'three hundred fifty six'
// console.log(toReadable(357)) // 'three hundred fifty seven'
// console.log(toReadable(358)) // 'three hundred fifty eight'
// console.log(toReadable(359)) // 'three hundred fifty nine'
// console.log(toReadable(360)) // 'three hundred sixty'
// console.log(toReadable(361)) // 'three hundred sixty one'
// console.log(toReadable(362)) // 'three hundred sixty two'
// console.log(toReadable(363)) // 'three hundred sixty three'
// console.log(toReadable(364)) // 'three hundred sixty four'
// console.log(toReadable(365)) // 'three hundred sixty five'
// console.log(toReadable(366)) // 'three hundred sixty six'
// console.log(toReadable(367)) // 'three hundred sixty seven'
// console.log(toReadable(368)) // 'three hundred sixty eight'
// console.log(toReadable(369)) // 'three hundred sixty nine'
// console.log(toReadable(370)) // 'three hundred seventy'
// console.log(toReadable(371)) // 'three hundred seventy one'
// console.log(toReadable(372)) // 'three hundred seventy two'
// console.log(toReadable(373)) // 'three hundred seventy three'
// console.log(toReadable(374)) // 'three hundred seventy four'
// console.log(toReadable(375)) // 'three hundred seventy five'
// console.log(toReadable(376)) // 'three hundred seventy six'
// console.log(toReadable(377)) // 'three hundred seventy seven'
// console.log(toReadable(378)) // 'three hundred seventy eight'
// console.log(toReadable(379)) // 'three hundred seventy nine'
// console.log(toReadable(380)) // 'three hundred eighty'
// console.log(toReadable(381)) // 'three hundred eighty one'
// console.log(toReadable(382)) // 'three hundred eighty two'
// console.log(toReadable(383)) // 'three hundred eighty three'
// console.log(toReadable(384)) // 'three hundred eighty four'
// console.log(toReadable(385)) // 'three hundred eighty five'
// console.log(toReadable(386)) // 'three hundred eighty six'
// console.log(toReadable(387)) // 'three hundred eighty seven'
// console.log(toReadable(388)) // 'three hundred eighty eight'
// console.log(toReadable(389)) // 'three hundred eighty nine'
// console.log(toReadable(390)) // 'three hundred ninety'
// console.log(toReadable(391)) // 'three hundred ninety one'
// console.log(toReadable(392)) // 'three hundred ninety two'
// console.log(toReadable(393)) // 'three hundred ninety three'
// console.log(toReadable(394)) // 'three hundred ninety four'
// console.log(toReadable(395)) // 'three hundred ninety five'
// console.log(toReadable(396)) // 'three hundred ninety six'
// console.log(toReadable(397)) // 'three hundred ninety seven'
// console.log(toReadable(398)) // 'three hundred ninety eight'
// console.log(toReadable(399)) // 'three hundred ninety nine'
// console.log(toReadable(400)) // 'four hundred'
// console.log(toReadable(401)) // 'four hundred one'
// console.log(toReadable(402)) // 'four hundred two'
// console.log(toReadable(403)) // 'four hundred three'
// console.log(toReadable(404)) // 'four hundred four'
// console.log(toReadable(405)) // 'four hundred five'
// console.log(toReadable(406)) // 'four hundred six'
// console.log(toReadable(407)) // 'four hundred seven'
// console.log(toReadable(408)) // 'four hundred eight'
// console.log(toReadable(409)) // 'four hundred nine'
// console.log(toReadable(410)) // 'four hundred ten'
// console.log(toReadable(411)) // 'four hundred eleven'
// console.log(toReadable(412)) // 'four hundred twelve'
// console.log(toReadable(413)) // 'four hundred thirteen'
// console.log(toReadable(414)) // 'four hundred fourteen'
// console.log(toReadable(415)) // 'four hundred fifteen'
// console.log(toReadable(416)) // 'four hundred sixteen'
// console.log(toReadable(417)) // 'four hundred seventeen'
// console.log(toReadable(418)) // 'four hundred eighteen'
// console.log(toReadable(419)) // 'four hundred nineteen'
// console.log(toReadable(420)) // 'four hundred twenty'
// console.log(toReadable(421)) // 'four hundred twenty one'
// console.log(toReadable(422)) // 'four hundred twenty two'
// console.log(toReadable(423)) // 'four hundred twenty three'
// console.log(toReadable(424)) // 'four hundred twenty four'
// console.log(toReadable(425)) // 'four hundred twenty five'
// console.log(toReadable(426)) // 'four hundred twenty six'
// console.log(toReadable(427)) // 'four hundred twenty seven'
// console.log(toReadable(428)) // 'four hundred twenty eight'
// console.log(toReadable(429)) // 'four hundred twenty nine'
// console.log(toReadable(430)) // 'four hundred thirty'
// console.log(toReadable(431)) // 'four hundred thirty one'
// console.log(toReadable(432)) // 'four hundred thirty two'
// console.log(toReadable(433)) // 'four hundred thirty three'
// console.log(toReadable(434)) // 'four hundred thirty four'
// console.log(toReadable(435)) // 'four hundred thirty five'
// console.log(toReadable(436)) // 'four hundred thirty six'
// console.log(toReadable(437)) // 'four hundred thirty seven'
// console.log(toReadable(438)) // 'four hundred thirty eight'
// console.log(toReadable(439)) // 'four hundred thirty nine'
// console.log(toReadable(440)) // 'four hundred forty'
// console.log(toReadable(441)) // 'four hundred forty one'
// console.log(toReadable(442)) // 'four hundred forty two'
// console.log(toReadable(443)) // 'four hundred forty three'
// console.log(toReadable(444)) // 'four hundred forty four'
// console.log(toReadable(445)) // 'four hundred forty five'
// console.log(toReadable(446)) // 'four hundred forty six'
// console.log(toReadable(447)) // 'four hundred forty seven'
// console.log(toReadable(448)) // 'four hundred forty eight'
// console.log(toReadable(449)) // 'four hundred forty nine'
// console.log(toReadable(450)) // 'four hundred fifty'
// console.log(toReadable(451)) // 'four hundred fifty one'
// console.log(toReadable(452)) // 'four hundred fifty two'
// console.log(toReadable(453)) // 'four hundred fifty three'
// console.log(toReadable(454)) // 'four hundred fifty four'
// console.log(toReadable(455)) // 'four hundred fifty five'
// console.log(toReadable(456)) // 'four hundred fifty six'
// console.log(toReadable(457)) // 'four hundred fifty seven'
// console.log(toReadable(458)) // 'four hundred fifty eight'
// console.log(toReadable(459)) // 'four hundred fifty nine'
// console.log(toReadable(460)) // 'four hundred sixty'
// console.log(toReadable(461)) // 'four hundred sixty one'
// console.log(toReadable(462)) // 'four hundred sixty two'
// console.log(toReadable(463)) // 'four hundred sixty three'
// console.log(toReadable(464)) // 'four hundred sixty four'
// console.log(toReadable(465)) // 'four hundred sixty five'
// console.log(toReadable(466)) // 'four hundred sixty six'
// console.log(toReadable(467)) // 'four hundred sixty seven'
// console.log(toReadable(468)) // 'four hundred sixty eight'
// console.log(toReadable(469)) // 'four hundred sixty nine'
// console.log(toReadable(470)) // 'four hundred seventy'
// console.log(toReadable(471)) // 'four hundred seventy one'
// console.log(toReadable(472)) // 'four hundred seventy two'
// console.log(toReadable(473)) // 'four hundred seventy three'
// console.log(toReadable(474)) // 'four hundred seventy four'
// console.log(toReadable(475)) // 'four hundred seventy five'
// console.log(toReadable(476)) // 'four hundred seventy six'
// console.log(toReadable(477)) // 'four hundred seventy seven'
// console.log(toReadable(478)) // 'four hundred seventy eight'
// console.log(toReadable(479)) // 'four hundred seventy nine'
// console.log(toReadable(480)) // 'four hundred eighty'
// console.log(toReadable(481)) // 'four hundred eighty one'
// console.log(toReadable(482)) // 'four hundred eighty two'
// console.log(toReadable(483)) // 'four hundred eighty three'
// console.log(toReadable(484)) // 'four hundred eighty four'
// console.log(toReadable(485)) // 'four hundred eighty five'
// console.log(toReadable(486)) // 'four hundred eighty six'
// console.log(toReadable(487)) // 'four hundred eighty seven'
// console.log(toReadable(488)) // 'four hundred eighty eight'
// console.log(toReadable(489)) // 'four hundred eighty nine'
// console.log(toReadable(490)) // 'four hundred ninety'
// console.log(toReadable(491)) // 'four hundred ninety one'
// console.log(toReadable(492)) // 'four hundred ninety two'
// console.log(toReadable(493)) // 'four hundred ninety three'
// console.log(toReadable(494)) // 'four hundred ninety four'
// console.log(toReadable(495)) // 'four hundred ninety five'
// console.log(toReadable(496)) // 'four hundred ninety six'
// console.log(toReadable(497)) // 'four hundred ninety seven'
// console.log(toReadable(498)) // 'four hundred ninety eight'
// console.log(toReadable(499)) // 'four hundred ninety nine'
// console.log(toReadable(500)) // 'five hundred'
// console.log(toReadable(501)) // 'five hundred one'
// console.log(toReadable(502)) // 'five hundred two'
// console.log(toReadable(503)) // 'five hundred three'
// console.log(toReadable(504)) // 'five hundred four'
// console.log(toReadable(505)) // 'five hundred five'
// console.log(toReadable(506)) // 'five hundred six'
// console.log(toReadable(507)) // 'five hundred seven'
// console.log(toReadable(508)) // 'five hundred eight'
// console.log(toReadable(509)) // 'five hundred nine'
// console.log(toReadable(510)) // 'five hundred ten'
// console.log(toReadable(511)) // 'five hundred eleven'
// console.log(toReadable(512)) // 'five hundred twelve'
// console.log(toReadable(513)) // 'five hundred thirteen'
// console.log(toReadable(514)) // 'five hundred fourteen'
// console.log(toReadable(515)) // 'five hundred fifteen'
// console.log(toReadable(516)) // 'five hundred sixteen'
// console.log(toReadable(517)) // 'five hundred seventeen'
// console.log(toReadable(518)) // 'five hundred eighteen'
// console.log(toReadable(519)) // 'five hundred nineteen'
// console.log(toReadable(520)) // 'five hundred twenty'
// console.log(toReadable(521)) // 'five hundred twenty one'
// console.log(toReadable(522)) // 'five hundred twenty two'
// console.log(toReadable(523)) // 'five hundred twenty three'
// console.log(toReadable(524)) // 'five hundred twenty four'
// console.log(toReadable(525)) // 'five hundred twenty five'
// console.log(toReadable(526)) // 'five hundred twenty six'
// console.log(toReadable(527)) // 'five hundred twenty seven'
// console.log(toReadable(528)) // 'five hundred twenty eight'
// console.log(toReadable(529)) // 'five hundred twenty nine'
// console.log(toReadable(530)) // 'five hundred thirty'
// console.log(toReadable(531)) // 'five hundred thirty one'
// console.log(toReadable(532)) // 'five hundred thirty two'
// console.log(toReadable(533)) // 'five hundred thirty three'
// console.log(toReadable(534)) // 'five hundred thirty four'
// console.log(toReadable(535)) // 'five hundred thirty five'
// console.log(toReadable(536)) // 'five hundred thirty six'
// console.log(toReadable(537)) // 'five hundred thirty seven'
// console.log(toReadable(538)) // 'five hundred thirty eight'
// console.log(toReadable(539)) // 'five hundred thirty nine'
// console.log(toReadable(540)) // 'five hundred forty'
// console.log(toReadable(541)) // 'five hundred forty one'
// console.log(toReadable(542)) // 'five hundred forty two'
// console.log(toReadable(543)) // 'five hundred forty three'
// console.log(toReadable(544)) // 'five hundred forty four'
// console.log(toReadable(545)) // 'five hundred forty five'
// console.log(toReadable(546)) // 'five hundred forty six'
// console.log(toReadable(547)) // 'five hundred forty seven'
// console.log(toReadable(548)) // 'five hundred forty eight'
// console.log(toReadable(549)) // 'five hundred forty nine'
// console.log(toReadable(550)) // 'five hundred fifty'
// console.log(toReadable(551)) // 'five hundred fifty one'
// console.log(toReadable(552)) // 'five hundred fifty two'
// console.log(toReadable(553)) // 'five hundred fifty three'
// console.log(toReadable(554)) // 'five hundred fifty four'
// console.log(toReadable(555)) // 'five hundred fifty five'
// console.log(toReadable(556)) // 'five hundred fifty six'
// console.log(toReadable(557)) // 'five hundred fifty seven'
// console.log(toReadable(558)) // 'five hundred fifty eight'
// console.log(toReadable(559)) // 'five hundred fifty nine'
// console.log(toReadable(560)) // 'five hundred sixty'
// console.log(toReadable(561)) // 'five hundred sixty one'
// console.log(toReadable(562)) // 'five hundred sixty two'
// console.log(toReadable(563)) // 'five hundred sixty three'
// console.log(toReadable(564)) // 'five hundred sixty four'
// console.log(toReadable(565)) // 'five hundred sixty five'
// console.log(toReadable(566)) // 'five hundred sixty six'
// console.log(toReadable(567)) // 'five hundred sixty seven'
// console.log(toReadable(568)) // 'five hundred sixty eight'
// console.log(toReadable(569)) // 'five hundred sixty nine'
// console.log(toReadable(570)) // 'five hundred seventy'
// console.log(toReadable(571)) // 'five hundred seventy one'
// console.log(toReadable(572)) // 'five hundred seventy two'
// console.log(toReadable(573)) // 'five hundred seventy three'
// console.log(toReadable(574)) // 'five hundred seventy four'
// console.log(toReadable(575)) // 'five hundred seventy five'
// console.log(toReadable(576)) // 'five hundred seventy six'
// console.log(toReadable(577)) // 'five hundred seventy seven'
// console.log(toReadable(578)) // 'five hundred seventy eight'
// console.log(toReadable(579)) // 'five hundred seventy nine'
// console.log(toReadable(580)) // 'five hundred eighty'
// console.log(toReadable(581)) // 'five hundred eighty one'
// console.log(toReadable(582)) // 'five hundred eighty two'
// console.log(toReadable(583)) // 'five hundred eighty three'
// console.log(toReadable(584)) // 'five hundred eighty four'
// console.log(toReadable(585)) // 'five hundred eighty five'
// console.log(toReadable(586)) // 'five hundred eighty six'
// console.log(toReadable(587)) // 'five hundred eighty seven'
// console.log(toReadable(588)) // 'five hundred eighty eight'
// console.log(toReadable(589)) // 'five hundred eighty nine'
// console.log(toReadable(590)) // 'five hundred ninety'
// console.log(toReadable(591)) // 'five hundred ninety one'
// console.log(toReadable(592)) // 'five hundred ninety two'
// console.log(toReadable(593)) // 'five hundred ninety three'
// console.log(toReadable(594)) // 'five hundred ninety four'
// console.log(toReadable(595)) // 'five hundred ninety five'
// console.log(toReadable(596)) // 'five hundred ninety six'
// console.log(toReadable(597)) // 'five hundred ninety seven'
// console.log(toReadable(598)) // 'five hundred ninety eight'
// console.log(toReadable(599)) // 'five hundred ninety nine'
// console.log(toReadable(600)) // 'six hundred'
// console.log(toReadable(601)) // 'six hundred one'
// console.log(toReadable(602)) // 'six hundred two'
// console.log(toReadable(603)) // 'six hundred three'
// console.log(toReadable(604)) // 'six hundred four'
// console.log(toReadable(605)) // 'six hundred five'
// console.log(toReadable(606)) // 'six hundred six'
// console.log(toReadable(607)) // 'six hundred seven'
// console.log(toReadable(608)) // 'six hundred eight'
// console.log(toReadable(609)) // 'six hundred nine'
// console.log(toReadable(610)) // 'six hundred ten'
// console.log(toReadable(611)) // 'six hundred eleven'
// console.log(toReadable(612)) // 'six hundred twelve'
// console.log(toReadable(613)) // 'six hundred thirteen'
// console.log(toReadable(614)) // 'six hundred fourteen'
// console.log(toReadable(615)) // 'six hundred fifteen'
// console.log(toReadable(616)) // 'six hundred sixteen'
// console.log(toReadable(617)) // 'six hundred seventeen'
// console.log(toReadable(618)) // 'six hundred eighteen'
// console.log(toReadable(619)) // 'six hundred nineteen'
// console.log(toReadable(620)) // 'six hundred twenty'
// console.log(toReadable(621)) // 'six hundred twenty one'
// console.log(toReadable(622)) // 'six hundred twenty two'
// console.log(toReadable(623)) // 'six hundred twenty three'
// console.log(toReadable(624)) // 'six hundred twenty four'
// console.log(toReadable(625)) // 'six hundred twenty five'
// console.log(toReadable(626)) // 'six hundred twenty six'
// console.log(toReadable(627)) // 'six hundred twenty seven'
// console.log(toReadable(628)) // 'six hundred twenty eight'
// console.log(toReadable(629)) // 'six hundred twenty nine'
// console.log(toReadable(630)) // 'six hundred thirty'
// console.log(toReadable(631)) // 'six hundred thirty one'
// console.log(toReadable(632)) // 'six hundred thirty two'
// console.log(toReadable(633)) // 'six hundred thirty three'
// console.log(toReadable(634)) // 'six hundred thirty four'
// console.log(toReadable(635)) // 'six hundred thirty five'
// console.log(toReadable(636)) // 'six hundred thirty six'
// console.log(toReadable(637)) // 'six hundred thirty seven'
// console.log(toReadable(638)) // 'six hundred thirty eight'
// console.log(toReadable(639)) // 'six hundred thirty nine'
// console.log(toReadable(640)) // 'six hundred forty'
// console.log(toReadable(641)) // 'six hundred forty one'
// console.log(toReadable(642)) // 'six hundred forty two'
// console.log(toReadable(643)) // 'six hundred forty three'
// console.log(toReadable(644)) // 'six hundred forty four'
// console.log(toReadable(645)) // 'six hundred forty five'
// console.log(toReadable(646)) // 'six hundred forty six'
// console.log(toReadable(647)) // 'six hundred forty seven'
// console.log(toReadable(648)) // 'six hundred forty eight'
// console.log(toReadable(649)) // 'six hundred forty nine'
// console.log(toReadable(650)) // 'six hundred fifty'
// console.log(toReadable(651)) // 'six hundred fifty one'
// console.log(toReadable(652)) // 'six hundred fifty two'
// console.log(toReadable(653)) // 'six hundred fifty three'
// console.log(toReadable(654)) // 'six hundred fifty four'
// console.log(toReadable(655)) // 'six hundred fifty five'
// console.log(toReadable(656)) // 'six hundred fifty six'
// console.log(toReadable(657)) // 'six hundred fifty seven'
// console.log(toReadable(658)) // 'six hundred fifty eight'
// console.log(toReadable(659)) // 'six hundred fifty nine'
// console.log(toReadable(660)) // 'six hundred sixty'
// console.log(toReadable(661)) // 'six hundred sixty one'
// console.log(toReadable(662)) // 'six hundred sixty two'
// console.log(toReadable(663)) // 'six hundred sixty three'
// console.log(toReadable(664)) // 'six hundred sixty four'
// console.log(toReadable(665)) // 'six hundred sixty five'
// console.log(toReadable(666)) // 'six hundred sixty six'
// console.log(toReadable(667)) // 'six hundred sixty seven'
// console.log(toReadable(668)) // 'six hundred sixty eight'
// console.log(toReadable(669)) // 'six hundred sixty nine'
// console.log(toReadable(670)) // 'six hundred seventy'
// console.log(toReadable(671)) // 'six hundred seventy one'
// console.log(toReadable(672)) // 'six hundred seventy two'
// console.log(toReadable(673)) // 'six hundred seventy three'
// console.log(toReadable(674)) // 'six hundred seventy four'
// console.log(toReadable(675)) // 'six hundred seventy five'
// console.log(toReadable(676)) // 'six hundred seventy six'
// console.log(toReadable(677)) // 'six hundred seventy seven'
// console.log(toReadable(678)) // 'six hundred seventy eight'
// console.log(toReadable(679)) // 'six hundred seventy nine'
// console.log(toReadable(680)) // 'six hundred eighty'
// console.log(toReadable(681)) // 'six hundred eighty one'
// console.log(toReadable(682)) // 'six hundred eighty two'
// console.log(toReadable(683)) // 'six hundred eighty three'
// console.log(toReadable(684)) // 'six hundred eighty four'
// console.log(toReadable(685)) // 'six hundred eighty five'
// console.log(toReadable(686)) // 'six hundred eighty six'
// console.log(toReadable(687)) // 'six hundred eighty seven'
// console.log(toReadable(688)) // 'six hundred eighty eight'
// console.log(toReadable(689)) // 'six hundred eighty nine'
// console.log(toReadable(690)) // 'six hundred ninety'
// console.log(toReadable(691)) // 'six hundred ninety one'
// console.log(toReadable(692)) // 'six hundred ninety two'
// console.log(toReadable(693)) // 'six hundred ninety three'
// console.log(toReadable(694)) // 'six hundred ninety four'
// console.log(toReadable(695)) // 'six hundred ninety five'
// console.log(toReadable(696)) // 'six hundred ninety six'
// console.log(toReadable(697)) // 'six hundred ninety seven'
// console.log(toReadable(698)) // 'six hundred ninety eight'
// console.log(toReadable(699)) // 'six hundred ninety nine'
// console.log(toReadable(700)) // 'seven hundred'
// console.log(toReadable(701)) // 'seven hundred one'
// console.log(toReadable(702)) // 'seven hundred two'
// console.log(toReadable(703)) // 'seven hundred three'
// console.log(toReadable(704)) // 'seven hundred four'
// console.log(toReadable(705)) // 'seven hundred five'
// console.log(toReadable(706)) // 'seven hundred six'
// console.log(toReadable(707)) // 'seven hundred seven'
// console.log(toReadable(708)) // 'seven hundred eight'
// console.log(toReadable(709)) // 'seven hundred nine'
// console.log(toReadable(710)) // 'seven hundred ten'
// console.log(toReadable(711)) // 'seven hundred eleven'
// console.log(toReadable(712)) // 'seven hundred twelve'
// console.log(toReadable(713)) // 'seven hundred thirteen'
// console.log(toReadable(714)) // 'seven hundred fourteen'
// console.log(toReadable(715)) // 'seven hundred fifteen'
// console.log(toReadable(716)) // 'seven hundred sixteen'
// console.log(toReadable(717)) // 'seven hundred seventeen'
// console.log(toReadable(718)) // 'seven hundred eighteen'
// console.log(toReadable(719)) // 'seven hundred nineteen'
// console.log(toReadable(720)) // 'seven hundred twenty'
// console.log(toReadable(721)) // 'seven hundred twenty one'
// console.log(toReadable(722)) // 'seven hundred twenty two'
// console.log(toReadable(723)) // 'seven hundred twenty three'
// console.log(toReadable(724)) // 'seven hundred twenty four'
// console.log(toReadable(725)) // 'seven hundred twenty five'
// console.log(toReadable(726)) // 'seven hundred twenty six'
// console.log(toReadable(727)) // 'seven hundred twenty seven'
// console.log(toReadable(728)) // 'seven hundred twenty eight'
// console.log(toReadable(729)) // 'seven hundred twenty nine'
// console.log(toReadable(730)) // 'seven hundred thirty'
// console.log(toReadable(731)) // 'seven hundred thirty one'
// console.log(toReadable(732)) // 'seven hundred thirty two'
// console.log(toReadable(733)) // 'seven hundred thirty three'
// console.log(toReadable(734)) // 'seven hundred thirty four'
// console.log(toReadable(735)) // 'seven hundred thirty five'
// console.log(toReadable(736)) // 'seven hundred thirty six'
// console.log(toReadable(737)) // 'seven hundred thirty seven'
// console.log(toReadable(738)) // 'seven hundred thirty eight'
// console.log(toReadable(739)) // 'seven hundred thirty nine'
// console.log(toReadable(740)) // 'seven hundred forty'
// console.log(toReadable(741)) // 'seven hundred forty one'
// console.log(toReadable(742)) // 'seven hundred forty two'
// console.log(toReadable(743)) // 'seven hundred forty three'
// console.log(toReadable(744)) // 'seven hundred forty four'
// console.log(toReadable(745)) // 'seven hundred forty five'
// console.log(toReadable(746)) // 'seven hundred forty six'
// console.log(toReadable(747)) // 'seven hundred forty seven'
// console.log(toReadable(748)) // 'seven hundred forty eight'
// console.log(toReadable(749)) // 'seven hundred forty nine'
// console.log(toReadable(750)) // 'seven hundred fifty'
// console.log(toReadable(751)) // 'seven hundred fifty one'
// console.log(toReadable(752)) // 'seven hundred fifty two'
// console.log(toReadable(753)) // 'seven hundred fifty three'
// console.log(toReadable(754)) // 'seven hundred fifty four'
// console.log(toReadable(755)) // 'seven hundred fifty five'
// console.log(toReadable(756)) // 'seven hundred fifty six'
// console.log(toReadable(757)) // 'seven hundred fifty seven'
// console.log(toReadable(758)) // 'seven hundred fifty eight'
// console.log(toReadable(759)) // 'seven hundred fifty nine'
// console.log(toReadable(760)) // 'seven hundred sixty'
// console.log(toReadable(761)) // 'seven hundred sixty one'
// console.log(toReadable(762)) // 'seven hundred sixty two'
// console.log(toReadable(763)) // 'seven hundred sixty three'
// console.log(toReadable(764)) // 'seven hundred sixty four'
// console.log(toReadable(765)) // 'seven hundred sixty five'
// console.log(toReadable(766)) // 'seven hundred sixty six'
// console.log(toReadable(767)) // 'seven hundred sixty seven'
// console.log(toReadable(768)) // 'seven hundred sixty eight'
// console.log(toReadable(769)) // 'seven hundred sixty nine'
// console.log(toReadable(770)) // 'seven hundred seventy'
// console.log(toReadable(771)) // 'seven hundred seventy one'
// console.log(toReadable(772)) // 'seven hundred seventy two'
// console.log(toReadable(773)) // 'seven hundred seventy three'
// console.log(toReadable(774)) // 'seven hundred seventy four'
// console.log(toReadable(775)) // 'seven hundred seventy five'
// console.log(toReadable(776)) // 'seven hundred seventy six'
// console.log(toReadable(777)) // 'seven hundred seventy seven'
// console.log(toReadable(778)) // 'seven hundred seventy eight'
// console.log(toReadable(779)) // 'seven hundred seventy nine'
// console.log(toReadable(780)) // 'seven hundred eighty'
// console.log(toReadable(781)) // 'seven hundred eighty one'
// console.log(toReadable(782)) // 'seven hundred eighty two'
// console.log(toReadable(783)) // 'seven hundred eighty three'
// console.log(toReadable(784)) // 'seven hundred eighty four'
// console.log(toReadable(785)) // 'seven hundred eighty five'
// console.log(toReadable(786)) // 'seven hundred eighty six'
// console.log(toReadable(787)) // 'seven hundred eighty seven'
// console.log(toReadable(788)) // 'seven hundred eighty eight'
// console.log(toReadable(789)) // 'seven hundred eighty nine'
// console.log(toReadable(790)) // 'seven hundred ninety'
// console.log(toReadable(791)) // 'seven hundred ninety one'
// console.log(toReadable(792)) // 'seven hundred ninety two'
// console.log(toReadable(793)) // 'seven hundred ninety three'
// console.log(toReadable(794)) // 'seven hundred ninety four'
// console.log(toReadable(795)) // 'seven hundred ninety five'
// console.log(toReadable(796)) // 'seven hundred ninety six'
// console.log(toReadable(797)) // 'seven hundred ninety seven'
// console.log(toReadable(798)) // 'seven hundred ninety eight'
// console.log(toReadable(799)) // 'seven hundred ninety nine'
// console.log(toReadable(800)) // 'eight hundred'
// console.log(toReadable(801)) // 'eight hundred one'
// console.log(toReadable(802)) // 'eight hundred two'
// console.log(toReadable(803)) // 'eight hundred three'
// console.log(toReadable(804)) // 'eight hundred four'
// console.log(toReadable(805)) // 'eight hundred five'
// console.log(toReadable(806)) // 'eight hundred six'
// console.log(toReadable(807)) // 'eight hundred seven'
// console.log(toReadable(808)) // 'eight hundred eight'
// console.log(toReadable(809)) // 'eight hundred nine'
// console.log(toReadable(810)) // 'eight hundred ten'
// console.log(toReadable(811)) // 'eight hundred eleven'
// console.log(toReadable(812)) // 'eight hundred twelve'
// console.log(toReadable(813)) // 'eight hundred thirteen'
// console.log(toReadable(814)) // 'eight hundred fourteen'
// console.log(toReadable(815)) // 'eight hundred fifteen'
// console.log(toReadable(816)) // 'eight hundred sixteen'
// console.log(toReadable(817)) // 'eight hundred seventeen'
// console.log(toReadable(818)) // 'eight hundred eighteen'
// console.log(toReadable(819)) // 'eight hundred nineteen'
// console.log(toReadable(820)) // 'eight hundred twenty'
// console.log(toReadable(821)) // 'eight hundred twenty one'
// console.log(toReadable(822)) // 'eight hundred twenty two'
// console.log(toReadable(823)) // 'eight hundred twenty three'
// console.log(toReadable(824)) // 'eight hundred twenty four'
// console.log(toReadable(825)) // 'eight hundred twenty five'
// console.log(toReadable(826)) // 'eight hundred twenty six'
// console.log(toReadable(827)) // 'eight hundred twenty seven'
// console.log(toReadable(828)) // 'eight hundred twenty eight'
// console.log(toReadable(829)) // 'eight hundred twenty nine'
// console.log(toReadable(830)) // 'eight hundred thirty'
// console.log(toReadable(831)) // 'eight hundred thirty one'
// console.log(toReadable(832)) // 'eight hundred thirty two'
// console.log(toReadable(833)) // 'eight hundred thirty three'
// console.log(toReadable(834)) // 'eight hundred thirty four'
// console.log(toReadable(835)) // 'eight hundred thirty five'
// console.log(toReadable(836)) // 'eight hundred thirty six'
// console.log(toReadable(837)) // 'eight hundred thirty seven'
// console.log(toReadable(838)) // 'eight hundred thirty eight'
// console.log(toReadable(839)) // 'eight hundred thirty nine'
// console.log(toReadable(840)) // 'eight hundred forty'
// console.log(toReadable(841)) // 'eight hundred forty one'
// console.log(toReadable(842)) // 'eight hundred forty two'
// console.log(toReadable(843)) // 'eight hundred forty three'
// console.log(toReadable(844)) // 'eight hundred forty four'
// console.log(toReadable(845)) // 'eight hundred forty five'
// console.log(toReadable(846)) // 'eight hundred forty six'
// console.log(toReadable(847)) // 'eight hundred forty seven'
// console.log(toReadable(848)) // 'eight hundred forty eight'
// console.log(toReadable(849)) // 'eight hundred forty nine'
// console.log(toReadable(850)) // 'eight hundred fifty'
// console.log(toReadable(851)) // 'eight hundred fifty one'
// console.log(toReadable(852)) // 'eight hundred fifty two'
// console.log(toReadable(853)) // 'eight hundred fifty three'
// console.log(toReadable(854)) // 'eight hundred fifty four'
// console.log(toReadable(855)) // 'eight hundred fifty five'
// console.log(toReadable(856)) // 'eight hundred fifty six'
// console.log(toReadable(857)) // 'eight hundred fifty seven'
// console.log(toReadable(858)) // 'eight hundred fifty eight'
// console.log(toReadable(859)) // 'eight hundred fifty nine'
// console.log(toReadable(860)) // 'eight hundred sixty'
// console.log(toReadable(861)) // 'eight hundred sixty one'
// console.log(toReadable(862)) // 'eight hundred sixty two'
// console.log(toReadable(863)) // 'eight hundred sixty three'
// console.log(toReadable(864)) // 'eight hundred sixty four'
// console.log(toReadable(865)) // 'eight hundred sixty five'
// console.log(toReadable(866)) // 'eight hundred sixty six'
// console.log(toReadable(867)) // 'eight hundred sixty seven'
// console.log(toReadable(868)) // 'eight hundred sixty eight'
// console.log(toReadable(869)) // 'eight hundred sixty nine'
// console.log(toReadable(870)) // 'eight hundred seventy'
// console.log(toReadable(871)) // 'eight hundred seventy one'
// console.log(toReadable(872)) // 'eight hundred seventy two'
// console.log(toReadable(873)) // 'eight hundred seventy three'
// console.log(toReadable(874)) // 'eight hundred seventy four'
// console.log(toReadable(875)) // 'eight hundred seventy five'
// console.log(toReadable(876)) // 'eight hundred seventy six'
// console.log(toReadable(877)) // 'eight hundred seventy seven'
// console.log(toReadable(878)) // 'eight hundred seventy eight'
// console.log(toReadable(879)) // 'eight hundred seventy nine'
// console.log(toReadable(880)) // 'eight hundred eighty'
// console.log(toReadable(881)) // 'eight hundred eighty one'
// console.log(toReadable(882)) // 'eight hundred eighty two'
// console.log(toReadable(883)) // 'eight hundred eighty three'
// console.log(toReadable(884)) // 'eight hundred eighty four'
// console.log(toReadable(885)) // 'eight hundred eighty five'
// console.log(toReadable(886)) // 'eight hundred eighty six'
// console.log(toReadable(887)) // 'eight hundred eighty seven'
// console.log(toReadable(888)) // 'eight hundred eighty eight'
// console.log(toReadable(889)) // 'eight hundred eighty nine'
// console.log(toReadable(890)) // 'eight hundred ninety'
// console.log(toReadable(891)) // 'eight hundred ninety one'
// console.log(toReadable(892)) // 'eight hundred ninety two'
// console.log(toReadable(893)) // 'eight hundred ninety three'
// console.log(toReadable(894)) // 'eight hundred ninety four'
// console.log(toReadable(895)) // 'eight hundred ninety five'
// console.log(toReadable(896)) // 'eight hundred ninety six'
// console.log(toReadable(897)) // 'eight hundred ninety seven'
// console.log(toReadable(898)) // 'eight hundred ninety eight'
// console.log(toReadable(899)) // 'eight hundred ninety nine'
// console.log(toReadable(900)) // 'nine hundred'
// console.log(toReadable(901)) // 'nine hundred one'
// console.log(toReadable(902)) // 'nine hundred two'
// console.log(toReadable(903)) // 'nine hundred three'
// console.log(toReadable(904)) // 'nine hundred four'
// console.log(toReadable(905)) // 'nine hundred five'
// console.log(toReadable(906)) // 'nine hundred six'
// console.log(toReadable(907)) // 'nine hundred seven'
// console.log(toReadable(908)) // 'nine hundred eight'
// console.log(toReadable(909)) // 'nine hundred nine'
// console.log(toReadable(910)) // 'nine hundred ten'
// console.log(toReadable(911)) // 'nine hundred eleven'
// console.log(toReadable(912)) // 'nine hundred twelve'
// console.log(toReadable(913)) // 'nine hundred thirteen'
// console.log(toReadable(914)) // 'nine hundred fourteen'
// console.log(toReadable(915)) // 'nine hundred fifteen'
// console.log(toReadable(916)) // 'nine hundred sixteen'
// console.log(toReadable(917)) // 'nine hundred seventeen'
// console.log(toReadable(918)) // 'nine hundred eighteen'
// console.log(toReadable(919)) // 'nine hundred nineteen'
// console.log(toReadable(920)) // 'nine hundred twenty'
// console.log(toReadable(921)) // 'nine hundred twenty one'
// console.log(toReadable(922)) // 'nine hundred twenty two'
// console.log(toReadable(923)) // 'nine hundred twenty three'
// console.log(toReadable(924)) // 'nine hundred twenty four'
// console.log(toReadable(925)) // 'nine hundred twenty five'
// console.log(toReadable(926)) // 'nine hundred twenty six'
// console.log(toReadable(927)) // 'nine hundred twenty seven'
// console.log(toReadable(928)) // 'nine hundred twenty eight'
// console.log(toReadable(929)) // 'nine hundred twenty nine'
// console.log(toReadable(930)) // 'nine hundred thirty'
// console.log(toReadable(931)) // 'nine hundred thirty one'
// console.log(toReadable(932)) // 'nine hundred thirty two'
// console.log(toReadable(933)) // 'nine hundred thirty three'
// console.log(toReadable(934)) // 'nine hundred thirty four'
// console.log(toReadable(935)) // 'nine hundred thirty five'
// console.log(toReadable(936)) // 'nine hundred thirty six'
// console.log(toReadable(937)) // 'nine hundred thirty seven'
// console.log(toReadable(938)) // 'nine hundred thirty eight'
// console.log(toReadable(939)) // 'nine hundred thirty nine'
// console.log(toReadable(940)) // 'nine hundred forty'
// console.log(toReadable(941)) // 'nine hundred forty one'
// console.log(toReadable(942)) // 'nine hundred forty two'
// console.log(toReadable(943)) // 'nine hundred forty three'
// console.log(toReadable(944)) // 'nine hundred forty four'
// console.log(toReadable(945)) // 'nine hundred forty five'
// console.log(toReadable(946)) // 'nine hundred forty six'
// console.log(toReadable(947)) // 'nine hundred forty seven'
// console.log(toReadable(948)) // 'nine hundred forty eight'
// console.log(toReadable(949)) // 'nine hundred forty nine'
// console.log(toReadable(950)) // 'nine hundred fifty'
// console.log(toReadable(951)) // 'nine hundred fifty one'
// console.log(toReadable(952)) // 'nine hundred fifty two'
// console.log(toReadable(953)) // 'nine hundred fifty three'
// console.log(toReadable(954)) // 'nine hundred fifty four'
// console.log(toReadable(955)) // 'nine hundred fifty five'
// console.log(toReadable(956)) // 'nine hundred fifty six'
// console.log(toReadable(957)) // 'nine hundred fifty seven'
// console.log(toReadable(958)) // 'nine hundred fifty eight'
// console.log(toReadable(959)) // 'nine hundred fifty nine'
// console.log(toReadable(960)) // 'nine hundred sixty'
// console.log(toReadable(961)) // 'nine hundred sixty one'
// console.log(toReadable(962)) // 'nine hundred sixty two'
// console.log(toReadable(963)) // 'nine hundred sixty three'
// console.log(toReadable(964)) // 'nine hundred sixty four'
// console.log(toReadable(965)) // 'nine hundred sixty five'
// console.log(toReadable(966)) // 'nine hundred sixty six'
// console.log(toReadable(967)) // 'nine hundred sixty seven'
// console.log(toReadable(968)) // 'nine hundred sixty eight'
// console.log(toReadable(969)) // 'nine hundred sixty nine'
// console.log(toReadable(970)) // 'nine hundred seventy'
// console.log(toReadable(971)) // 'nine hundred seventy one'
// console.log(toReadable(972)) // 'nine hundred seventy two'
// console.log(toReadable(973)) // 'nine hundred seventy three'
// console.log(toReadable(974)) // 'nine hundred seventy four'
// console.log(toReadable(975)) // 'nine hundred seventy five'
// console.log(toReadable(976)) // 'nine hundred seventy six'
// console.log(toReadable(977)) // 'nine hundred seventy seven'
// console.log(toReadable(978)) // 'nine hundred seventy eight'
// console.log(toReadable(979)) // 'nine hundred seventy nine'
// console.log(toReadable(980)) // 'nine hundred eighty'
// console.log(toReadable(981)) // 'nine hundred eighty one'
// console.log(toReadable(982)) // 'nine hundred eighty two'
// console.log(toReadable(983)) // 'nine hundred eighty three'
// console.log(toReadable(984)) // 'nine hundred eighty four'
// console.log(toReadable(985)) // 'nine hundred eighty five'
// console.log(toReadable(986)) // 'nine hundred eighty six'
// console.log(toReadable(987)) // 'nine hundred eighty seven'
// console.log(toReadable(988)) // 'nine hundred eighty eight'
// console.log(toReadable(989)) // 'nine hundred eighty nine'
// console.log(toReadable(990)) // 'nine hundred ninety'
// console.log(toReadable(991)) // 'nine hundred ninety one'
// console.log(toReadable(992)) // 'nine hundred ninety two'
// console.log(toReadable(993)) // 'nine hundred ninety three'
// console.log(toReadable(994)) // 'nine hundred ninety four'
// console.log(toReadable(995)) // 'nine hundred ninety five'
// console.log(toReadable(996)) // 'nine hundred ninety six'
// console.log(toReadable(997)) // 'nine hundred ninety seven'
// console.log(toReadable(998)) // 'nine hundred ninety eight'
// console.log(toReadable(999)) // 'nine hundred ninety nine'
